name: Composer

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Validate composer.json
      run: composer validate --strict